[unix_http_server]
file=/tmp/supervisor.sock
; how the supervisord communicates with itself internally 
[supervisord]
nodaemon=true ;needs to be true so it can run 
;in the foreground and docker will not quit after the process is done
logfile=/tmp/supervisord.log

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
;boilerplate thats required 
[supervisorctl]
serverurl=unix:///tmp/supervisor.sock
;used to control supervisord from the commandline 
[program:mainapp]
command=uvicorn main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
;main app setup through docker on port 8000
[program:python39]
command=uvicorn main:app --host 0.0.0.0 --port 8001
directory=/app/runtimes/python39
autostart=true
autorestart=true
;runtimes/python3.9 language version setup on port 8001
[program:python311]
command=uvicorn main:app --host 0.0.0.0 --port 8002
directory=/app/runtimes/python311
autostart=true
autorestart=true
;runtimes/python3.11 language version setup on port 8002
[program:python312]
command=uvicorn main:app --host 0.0.0.0 --port 8003
directory=/app/runtimes/python312
autostart=true
autorestart=true
;runtimes/python3.12 language version setup on port 8003
[program:python313]
command=uvicorn main:app --host 0.0.0.0 --port 8004
directory=/app/runtimes/python313
autostart=true
autorestart=true
;runtimes/python3.13 language version setup on port 8004
[program:node18]
command=uvicorn main:app --host 0.0.0.0 --port 8005
directory=/app/runtimes/node18
autostart=true
autorestart=true
;runtimes/node18 language version setup on port 8005
[program:node20]
command=uvicorn main:app --host 0.0.0.0 --port 8006
directory=/app/runtimes/node20
autostart=true
autorestart=true
;runtimes/node20 language version setup on port 8006
[program:node24]
command=uvicorn main:app --host 0.0.0.0 --port 8007
directory=/app/runtimes/node24
autostart=true
autorestart=true
;runtimes/node24 language version setup on port 8007
[program:java21]
command=uvicorn main:app --host 0.0.0.0 --port 8008
directory=/app/runtimes/java21
autostart=true
autorestart=true
;runtimes/java21 langauge version setup on port 8008 
[program:php82] 
command=uvicorn main:app --host 0.0.0.0 --port 8009
directory=/app/runtimes/php82
autostart=true
autorestart=true
;runtimes/php82 language version setup on port 8009 
