[unix_http_server]
file=/tmp/supervisor.sock
; how the supervisord communicates with itself internally 
[supervisord]
nodaemon=true ;needs to be true so it can run 
;in the foreground and docker will not quit after the process is done
logfile=/tmp/supervisord.log

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
;boilerplate thats required 
[supervisorctl]
serverurl=unix:///tmp/supervisor.sock
;used to control supervisord from the commandline 
[program:mainapp]
command=uvicorn main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
;main app setup through docker on port 8000 
[program:python313]
command=uvicorn main:app --host 0.0.0.0 --port 8001
directory=/app/runtimes/python313
autostart=true
autorestart=true
;runtimes/python3.13 language version setup on port 8001
[program:node24]
command=uvicorn main:app --host 0.0.0.0 --port 8002
directory=/app/runtimes/node24
autostart=true
autorestart=true
;runstimes/node24 language version setup on port 8002